#Nicole E Soltis
#101118

#-------------------------------------------------------------------------
rm(list=ls())
setwd("~/Projects/BcSolGWAS/")
ModDat <- read.csv("data/preGWAS/SlBc_ModelData.csv")

#remove isolates missing from one experiment
SlSumm <- as.data.frame(with(ModDat, table(Igeno,ExpBlock)))
#missing Exps: Gallo3 (96a), 94.1 (96b)
OgDat <- ModDat
ModDat <- subset(ModDat, Igeno != "Gallo3")
ModDat <- subset(ModDat, Igeno != "94.1")
ModDat <- ModDat[,-c(1)]
ModDat$Igeno <- droplevels(ModDat$Igeno)

#new wilcoxon test on model-adjusted lesion sizes

#read in lsmeans outputs ... do I need to redo the model for lsmeans?
#this is the file generated by 04_LSMEANS.R
setwd("~/Projects/BcSolGWAS")
lsmdat <- read.csv("results/output/lsmeans/BcSlGWAS_lsmeans.csv")

ModDat.plant <- ddply(lsmdat, c("Igeno", "Plant"), summarise, 
                      mLS = mean(Estimate))
ModDat.plant$Plant.Num<- as.numeric(ModDat.plant$Plant)

#now subset data frame to look at pairs of plant genotypes
outdf <- as.data.frame(NULL)
newdata <- NULL
library(data.table)
for (j in c(1:12)){
  for (i in c(1:12)){
    print(unique(newdata$Plant.Num))
    tryCatch({
      newdata <- ModDat.plant[ ModDat.plant$Plant.Num %in% c(i,j), ]
      newout <- wilcox.test(newdata$mLS ~ newdata$Plant.Num)
      #print(newout)
      df <- as.data.frame(newout$statistic)
      setDT(df, keep.rownames = T)[]
      df$Plant1 <- unique(newdata$Plant.Num)[1]
      df$Plant2 <- unique(newdata$Plant.Num)[2]
      df$sig <- newout$p.value
      outdf = rbind(outdf, df)
      if (i==j) stop("Urgh, these are the same group !")
    }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
    #print(newout$statistic)
    #print(newout$p.value)
  }
}
outdf2 <- unique(outdf)
outdf2$fdr.p <- p.adjust(outdf2$sig, method="fdr")
write.csv(outdf2, "paper/Submissions/PlantCell/TPC revision/Table2_Wilcox_LSM.csv")

#-------------------------------------------------------------
#and model-corrected wilcox test for domestication!
rm(list=ls())
setwd("~/Projects/BcSolGWAS/")
ModDat <- read.csv("data/preGWAS/SlBc_ModelData.csv")

#remove isolates missing from one experiment
SlSumm <- as.data.frame(with(ModDat, table(Igeno,ExpBlock)))
#missing Exps: Gallo3 (96a), 94.1 (96b)
OgDat <- ModDat
ModDat <- subset(ModDat, Igeno != "Gallo3")
ModDat <- subset(ModDat, Igeno != "94.1")
ModDat <- ModDat[,-c(1)]
ModDat$Igeno <- droplevels(ModDat$Igeno)

#new wilcoxon test on model-adjusted lesion sizes

#read in lsmeans outputs ... do I need to redo the model for lsmeans?
#this is the file generated by 04_LSMEANS.R
setwd("~/Projects/BcSolGWAS")
lsmdat <- read.csv("results/output/lsmeans/BcSlGWAS_lsmeans.csv")
library(plyr)
ModDat.spp <- ddply(lsmdat, c("Igeno", "Species"), summarise, 
                      mLS = mean(Estimate))
wilcox.test(ModDat.spp$mLS ~ ModDat.spp$Species)
