#Nicole E Soltis
#101118

#-------------------------------------------------------------------------
rm(list=ls())
setwd("~/Projects/BcSolGWAS/")
ModDat <- read.csv("data/preGWAS/SlBc_ModelData.csv")

#remove isolates missing from one experiment
SlSumm <- as.data.frame(with(ModDat, table(Igeno,ExpBlock)))
#missing Exps: Gallo3 (96a), 94.1 (96b)
OgDat <- ModDat
ModDat <- subset(ModDat, Igeno != "Gallo3")
ModDat <- subset(ModDat, Igeno != "94.1")
ModDat <- ModDat[,-c(1)]
ModDat$Igeno <- droplevels(ModDat$Igeno)

#new wilcoxon test on model-adjusted lesion sizes

#read in lsmeans outputs ... do I need to redo the model for lsmeans?
#this is the file generated by 04_LSMEANS.R
setwd("~/Projects/BcSolGWAS")
lsmdat <- read.csv("results/output/lsmeans/BcSlGWAS_lsmeans.csv")

ModDat.plant <- ddply(lsmdat, c("Igeno", "Plant"), summarise, 
                      mLS = mean(Estimate))
ModDat.plant$Plant.Num<- as.numeric(ModDat.plant$Plant)

#now subset data frame to look at pairs of plant genotypes
outdf <- as.data.frame(NULL)
newdata <- NULL
library(data.table)
for (j in c(1:12)){
  for (i in c(1:12)){
    print(unique(newdata$Plant.Num))
    tryCatch({
      newdata <- ModDat.plant[ ModDat.plant$Plant.Num %in% c(i,j), ]
      newout <- wilcox.test(newdata$mLS ~ newdata$Plant.Num)
      #print(newout)
      df <- as.data.frame(newout$statistic)
      setDT(df, keep.rownames = T)[]
      df$Plant1 <- unique(newdata$Plant.Num)[1]
      df$Plant2 <- unique(newdata$Plant.Num)[2]
      df$sig <- newout$p.value
      outdf = rbind(outdf, df)
      if (i==j) stop("Urgh, these are the same group !")
    }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
    #print(newout$statistic)
    #print(newout$p.value)
  }
}
outdf2 <- unique(outdf)
outdf2$fdr.p <- p.adjust(outdf2$sig, method="fdr")
write.csv(outdf2, "paper/Submissions/PlantCell/TPC revision/Table2_Wilcox_LSM.csv")

#-----------------------------------------------------------------
#original wilcoxon test on raw lesions
#wilcoxon signed-rank test between each PAIR of host genotypes
#on isolate means
ModDat.plant <- ddply(ModDat, c("Igeno", "PlGenoNm"), summarise, 
                      mLS = mean(Scale.LS),
                      sdLS = sd(Scale.LS))
ModDat.plant$Plant.Num<- as.numeric(ModDat.plant$PlGenoNm)

#now subset data frame to look at pairs of plant genotypes
outdf <- as.data.frame(NULL)
newdata <- NULL
library(data.table)
for (j in c(1:12)){
  for (i in c(1:12)){
    print(unique(newdata$Plant.Num))
    tryCatch({
      newdata <- ModDat.plant[ ModDat.plant$Plant.Num %in% c(i,j), ]
      newout <- wilcox.test(newdata$mLS ~ newdata$Plant.Num)
      #print(newout)
      df <- as.data.frame(newout$statistic)
      setDT(df, keep.rownames = T)[]
      df$Plant1 <- unique(newdata$Plant.Num)[1]
      df$Plant2 <- unique(newdata$Plant.Num)[2]
      df$sig <- newout$p.value
      outdf = rbind(outdf, df)
      if (i==j) stop("Urgh, these are the same group !")
    }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
    #print(newout$statistic)
    #print(newout$p.value)
  }
}
outdf2 <- unique(outdf)
outdf2$fdr.p <- p.adjust(outdf2$sig, method="fdr")
write.csv(outdf2, "paper/plots/ActualPaper/Supp/WilcoxBYPLANT_out.csv")

#now, make a rank-order plot of only the most extreme pair (smallest p-value from wilcoxon)
newdata <- ModDat.plant[ ModDat.plant$Plant.Num %in% c(1,9), ]
levels(newdata$PlGenoNm) <- c(levels(newdata$PlGenoNm), "LA0410") 
newdata$PlGenoNm[newdata$PlGenoNm == "LA410"]  <- "LA0410" 
tiff("paper/plots/FigR5/FigR5_Sl_LesionSize_IntMean_wilcoxtop.tif", width=3.5, height=4, units='in', res=600)
ggplot(newdata, aes(x = PlGenoNm, y = mLS, group=factor(Igeno)))+
  theme_bw()+
  geom_line(size=0.5, alpha=0.4, show.legend = F)+
  ylim(0,1.7)+
  theme(text = element_text(size=14), axis.text.x = element_text(size=14), axis.text.y = element_text(size=14), strip.background = element_blank())+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  labs(y=expression(Lesion ~ Area ~ (cm^{2})), x=element_blank())
dev.off()

t.test(ModDat.cv$cvLS, ModDat.cv$Species.Num)
wilcox.test(ModDat.cv$cvLS, ModDat.cv$Species.Num)